import type { Metadata } from "next";

import "@/components/sass/Globals.scss"

import { Raleway as RalewayFont } from "next/font/google";

const Raleway = RalewayFont({ subsets: ["latin"] });

import dynamic from "next/dynamic";

const Header = dynamic(() => import("@/components/layout/Header"), {
  ssr: false,
});

const Footer = dynamic(() => import("@/components/layout/Footer"), {
  ssr: false,
});

export const metadata: Metadata = {
  title: "Blog Mods",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Raleway.className}>
        <main>
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
